### ISSUE TITLE
Example for pruning ResNet

### ISSUE THREAD

**Issue by ganji15** [babajide07/Redundant-Feature-Pruning-Pytorch-Implementation#1]
Your works are extremely impressive and inspiring.

The idea for pruning VGG is straightforward and is easy to follow, however, it seems to be more complicated for pruning ResNet. Therefore, I wonder whether you plan to provide an example for pruning ResNet?

Thanks!

**Comment by babajide07** [comment]
Thanks for checking out our code. Sure, we will soon release the code for ResNet 56 and 110.

**Comment by ganji15** [comment]
Hi, @babajide07 

Thanks for your reply.

Actually, I am confused about how to prune the residual block without the 1x1 conv projection shortcut. The previous related work (in the paper "Pruning Filters for Efficient ConvNets") has shown how to prune a residual block with a 1x1 conv projection shortcut, which sounds logical and reasonable, however, it is not clear how to prune a residual block without that 1x1 conv projection shortcut. As we known, most residual blocks in the ResNet have no 1x1 conv projection shortcut, i.e., their shortcuts contain no parameters. If we prune filters of both conv layers in such a residual block, the channels of the residual branch and the main branch might be different, and thus F(x) and the residual x cannot be added directly.  Could you please explain how would you address this problem in your implementation?

I will greatly appreciate your kind help.

Thanks!

**Comment by babajide07** [comment]
This is why we only prune the first Conv layer features of each residual block in ResNet 56 and 110, for instance. By so doing, we avoid your aforementioned problem.

**Comment by ganji15** [comment]
Thanks, @babajide07

It is an acceptable compromise. 

Thanks so much for your kind help!

**Comment by MClarkTurner** [comment]
Again as @ganji15  mentioned, your work is very interesting and much appreciated. Since the original post was first made have you uploaded the ResNet pruning files? I cannot seem to find them.
